// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngfwfvullqrgosnwguou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZndmdnVsbHFyZ29zbndndW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDIxOTMsImV4cCI6MjA1OTYxODE5M30.2XDz4RABTeEKvgCz0bYeXrCdUs8RK7dOV9KVZxrd32U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);